import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {cn} from "@/lib/utils"

import { Sidebar } from '@/components/sidebar/index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-scream bg-background font-sans antialiased",
        inter.className
      )}>
        <Sidebar/>
        {children}
        </body>
    </html>
  )
}
